### ISSUE TITLE
Update Officer Bio's to reflect correct positions

### ISSUE THREAD

**Issue by keisenb** [ksu-acm/acm.cs.ksu.edu#38]
Some of the officers have the wrong position from last year. Need to either update these or request updated bio's from the officers.

**Comment by daytonltaylor** [comment]
the only problem i saw was capitalizing "President" in atodd's bio and changing Clay's bio to reflect his new position. Is this correct? Otherwise, the other bios i saw simply had no reference to the position they held, so if we want that, then it would probably be best to request bios from everyone. The choice is up to you guys.

**Comment by keisenb** [comment]
Yes those are the only changes currently. Would be good to get bio's from everyone who doesn't have one. Don't need to have position in the bio.

**Comment by daytonltaylor** [comment]
ok, ill do a pull request for those changes and then will see what everyone wants to do
